// pages/main.js

import {getnewRequest,gethotRequest,getlikedRequest,searchBlog} from "../../utils/apis"
var hcurrent=1,ncurrent=1,lcurrent=1,scurrent=1
var app=getApp();
var load=0
Page({
  data: {
      userName:'',
      userIcon:'',
      topHeight:(app.globalData.capsule.top - app.globalData.system.statusBarHeight) * 2 + app.globalData.capsule.height + app.globalData.system.statusBarHeight,
      list:[],
      saying:'为之，则难者亦易矣',
      num:0,
      details:'',
      keyword:'',
      loading:0,
      isdata:0
  },
  /**
   * 生命周期函数--监听页面加载
   */
  onLoad(options) {
    this.setData({
      userName:app.globalData.userInfo.nickName,
      userIcon:app.globalData.userInfo.icon
    })
    this.getNew()
  },
  onShow(){
    if(app.globalData.refresh==1){
      this.getNew()
      app.globalData.refresh=0
    }
  },
  search(){
    load=0
    scurrent=1
    this.setData({
      isdata:0
    })
    searchBlog({
      token:wx.getStorageSync('token'),
      keyword:this.data.keyword,
      scurrent
    }).then(res=>{
      load=1
      if(res.data.data.length==0){
        wx.showToast({
          title: '没有相关帖子',
          icon:'none'
        })
      }
      else{
        this.setData({
          num:3,
          list:res.data.data,
        })
      }
    })
  },

  getNew(){
    load=0
    this.setData({
      list:'',
      loading:1,
      num:0,
      isdata:0
    })
    ncurrent=1
    getnewRequest({
      token:wx.getStorageSync('token'),
      ncurrent
    }).then(res=>{
      load=1
      console.log("最新帖子")
      console.log(res.data)
      this.setData({
        list:res.data.data,
        loading:0
      }) 
    })
    .catch(err=>{
      console.log(err)
    })
  },

  getLike() {
    load=0
    this.setData({
      loading:1,
      list:'',
      num:1,
      isdata:0
    })
    lcurrent=1
    getlikedRequest({
      token:wx.getStorageSync('token'),
      lcurrent
    }).then(res=>{
      load=1
      this.setData({
        loading:0,
        list:res.data.data,
      })
    })
  },

  getHot() {
    load=0
    this.setData({
      list:'',
      loading:1,
      num:2,
      isdata:0
    })
    hcurrent=1
    gethotRequest({
      token:wx.getStorageSync('token'),
      hcurrent
    }).then(res=>{
      load=1
      console.log("最热帖子")
      console.log(res)
      this.setData({
        loading:0,
        list:res.data.data,
      })
    })
  },
 
  onReachBottom() {
    if(load==1&&!this.data.isdata){
      this.setData({
        loading:1
      })
      if(this.data.num==0){
        ncurrent++
        getnewRequest({
          token:wx.getStorageSync('token'),
          ncurrent
        }).then(res=>{
          this.setData({
            loading:0
          })
          if(res.data.data.length==0){
            this.setData({
              isdata:1
            })
          }
          console.log("最新帖子")
          console.log(res.data.data)
          this.setData({
            list:this.data.list.concat(res.data.data)
          })
          
        })
      }
      if(this.data.num==1){
        lcurrent++
        getlikedRequest({
          token:wx.getStorageSync('token'),
          lcurrent
        }).then(res=>{
          this.setData({
            loading:0
          })
          if(res.data.data.length==0){
            this.setData({
              isdata:1
            })
          }
          console.log("猜你喜欢")
          console.log(res.data.data)
          this.setData({
            list:this.data.list.concat(res.data.data)
          })
        })
      }
      if(this.data.num==2){
        hcurrent++
        gethotRequest({
          token:wx.getStorageSync('token'),
          hcurrent
        }).then(res=>{
          this.setData({
            loading:0
          })
          if(res.data.data.length==0){
            this.setData({
              isdata:1
            })
          }
          console.log("最热帖子")
          console.log(res.data.data)
          this.setData({
            list:this.data.list.concat(res.data.data)
          })
        })
      }
      if(this.data.num==3){
        scurrent++
        searchBlog({
          token:wx.getStorageSync('token'),
          keyword:this.data.keyword,
          scurrent
        }).then(res=>{
          this.setData({
            loading:0
          })
          if(res.data.data.length==0){
            this.setData({
              isdata:1
            })
          }
          else{
            this.setData({
              list:this.data.list.concat(res.data.data)
            })
          }
        })
      }
    }
  },
})